language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
script: "bundle exec rake coverage"
gemfile:
  - gemfiles/rails2.gemfile
  - gemfiles/rails3.gemfile
  - gemfiles/rails4.gemfile
matrix:
  exclude:
    - rvm: 1.9.3
      gemfile: gemfiles/rails2.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/rails2.gemfile
    - rvm: 1.8.7
      gemfile: gemfiles/rails4.gemfile
    - rvm: 1.9.2
      gemfile: gemfiles/rails4.gemfile
notifications:
  email:
    - support@travellink.com.au
  flowdock: e69dcafad1fea15c6b8c76e9ced965af
